import os
import signal
from time import sleep, time
import json

DNS_ZONE = os.environ['WGHOSTS_ZONE']
SERVER_NAME = os.environ['WGHOSTS_SERVER']
SLEEP = int(os.environ.get('WGHOSTS_SLEEP', 3))

WGFILE = 'config/wg/wg0.json'
HOSTSFILE = 'config/dns/wghosts.conf'

HOSTSFILE_NOTE = """
# Note: Do not edit this file directly.
# Your changes will be overwritten!

"""

def upd():
    print('Config update:')
    with open(WGFILE, 'r') as f:
        j = json.load(f)
    server = (j['server']['address'], SERVER_NAME)
    clients = sorted([(c['address'], c['name']) for c in j['clients'].values()])
    hosts = '\n'.join([f'{a} {n}.{DNS_ZONE}' for a, n in [server] + clients])
    conf = HOSTSFILE_NOTE + 'hosts {\n' + hosts + '\nfallthrough\n}'
    print(conf)
    with open(HOSTSFILE, 'w') as f:
        f.write(conf)


def terminate(signal,frame):
    exit(0)


signal.signal(signal.SIGTERM, terminate)

prev_mt = 0
prev_changed = True
while True:
    try:
        mt = os.stat(WGFILE).st_mtime
        changed = mt != prev_mt
        if prev_changed and not changed:
            upd()
    except FileNotFoundError:
        mt = time()
        changed = True
    prev_mt = mt
    prev_changed = changed

    sleep(SLEEP)
